### ISSUE TITLE
Follow

### ISSUE THREAD

**Issue by bestdevmgp** [B9ND/memoa-server#11]
Let's make bookmark feature

**Comment by Andrez092** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by bestdevmgp** [comment]
팔로우 기능 개발 완료하였습니다.
